# Generated by Django 4.1.7 on 2023-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.CharField(choices=[('1-2 Days', '3 Days - 1 Week'), ('1 Week - 2 Weeks', 'Other')], default='1-2 Days', max_length=100, null=True),
        ),
    ]
