# Generated by Django 4.1.7 on 2023-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_merge_20230506_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Serial Number',
        ),
        migrations.AddField(
            model_name='product',
            name='sn',
            field=models.PositiveIntegerField(null=True, verbose_name='Serial Number'),
        ),
    ]
