# Generated by Django 4.1.7 on 2023-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_product_serial number_product_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Days To Loan',
        ),
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.CharField(choices=[('1-2 Days', '1-2 Days'), ('3 Days - 1 Week', '3 Days - 1 Week'), ('1 Week - 2 Weeks', '1 Week - 2 Weeks'), ('Other', 'Other')], default='1-2 Days', max_length=100, null=True, verbose_name='Days To Loan'),
        ),
    ]
