# Generated by Django 4.1.7 on 2023-05-19 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returnDate',
            field=models.DateTimeField(default=datetime.date(2023, 5, 19)),
        ),
    ]
