# Generated by Django 4.1.7 on 2023-05-19 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_order_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returnDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
