# Generated by Django 4.1.7 on 2023-05-19 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_product_days_alter_order_returndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extendedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Extended Date'),
        ),
    ]
