# Generated by Django 4.1.7 on 2023-05-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_order_extendeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extendRequested',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
