# Generated by Django 4.1.7 on 2023-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_order_extendrequested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extendRequested',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('NotRequested', 'NotRequested')], default='Pending', max_length=12),
        ),
    ]
