# Generated by Django 4.1.7 on 2023-05-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_order_extendrequested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cables', 'Cables'), ('Lights', 'Lights'), ('Convertors', 'Convertors'), ('Projectors', 'Projectors'), ('Tripod', 'Tripod'), ('Apple', 'Apple'), ('Rec', 'Rec'), ('Camera', 'Camera')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sn',
            field=models.CharField(max_length=20, null=True, verbose_name='Serial Number'),
        ),
    ]
