# Generated by Django 4.1.7 on 2023-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
