# Generated by Django 4.1.7 on 2023-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_visible_to_manager',
            field=models.BooleanField(default=True),
        ),
    ]
