# Generated by Django 4.1.7 on 2023-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_product_days to loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Days To Loan',
            field=models.CharField(choices=[('1-2 Days', '1-2 Days'), ('3 Days - 1 Week', '3 Days - 1 Week'), ('1 Week - 2 Weeks', '1 Week - 2 Weeks'), ('Other', 'Other')], default='1-2 Days', max_length=100, null=True),
        ),
    ]
