# Generated by Django 4.1.7 on 2023-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_product_time_product_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='days',
        ),
        migrations.AddField(
            model_name='product',
            name='Days To Loan',
            field=models.CharField(choices=[('1-2 Days', '1-2 Days'), ('3 Days - 1 Week', '3 Days - 1 Week'), ('1 Week - 2 Weeks', '1 Week - 2 Weeks'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Serial Number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
