# Generated by Django 4.1.7 on 2023-05-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_days to loan'),
        ('dashboard', '0007_alter_product_days to loan'),
    ]

    operations = [
    ]
