# Generated by Django 4.1.7 on 2023-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_product_days to loan_product_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
