# Generated by Django 4.1.7 on 2023-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_order_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
