# Generated by Django 4.1.7 on 2023-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_order_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
