# Generated by Django 4.1.7 on 2023-05-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.product'),
        ),
    ]
