# Generated by Django 4.1.7 on 2023-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Cables', 'Cables'), ('Lights', 'Lights'), ('Convertors', 'Convertors'), ('Projectors', 'Projectors'), ('Tripod', 'Tripod'), ('Apple', 'Apple'), ('Rec', 'Rec'), ('Camera', 'Camera')], max_length=100, null=True),
        ),
    ]
