# Generated by Django 4.1.7 on 2023-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_visible_to_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_visible_to_student',
            field=models.BooleanField(default=True),
        ),
    ]
